export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const LOADING = 'LOADING';
export const UPDATE_NOTIFICATIONS_OPEN = 'UPDATE_NOTIFICATIONS_OPEN';